global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#lushnikov_dmitriy'
