kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: SIvF00D02xvQHFuiWWHpsnd557oUSHMmr6wdA=
      - identity: {}
